### ISSUE TITLE
Unrelated: Looking to compile your dim3 engine.

### ISSUE THREAD

**Issue by netkommander** [ggadwa/WSJS#1]
Hi there Brian, 

Been a big fan of you since you had the dim3 engine. I'm having quite the issue compiling it on a Modern Visual Studio 2015 Community version. I even tried to compile it via Visual Studio 6. But to no avail. It gives me a linker issue. 

I'll be willing to share it if you are interested in helping me out. I'm glad to see you're looking into new projects!

**Comment by ggadwa** [comment]
What's the linker issue?  Some of the libraries are probably super old, and I suspect it's probably a 32 bit issue which could be a pretty big fix.  It's a really old code base, but I'll see what help I might be able to give!

**Comment by netkommander** [comment]
Hey man, good to see you! 

I'm going to try to compile this again on a modern machine. I ALMOST got it to work on a VC6++ WinXP VM. I'll attach both screenshots when I'm finished so you can take a look.

**Comment by netkommander** [comment]
![image](https://user-images.githubusercontent.com/64513006/81330220-cb029300-906d-11ea-8a99-8ae2e5715f96.png)

Here's one of the errors I get when compiling under VC++ 6. I First compiled in this order
BaseUtility 
Dim3Map 
Model
Then go for Engine and it does this 

All the files are in the win32includes dim3 folder.

**Comment by netkommander** [comment]
Here's another problem that I am having. I have seemed to move it in the right direction. Again this is the VC++ 6 compilation. 
![image](https://user-images.githubusercontent.com/64513006/81342189-cf847700-9080-11ea-86ef-8d43a4634257.png)

I am simply unsure because this file is not located within the "release" folder, so I'm at a stuck road atm. I was wondering if there is anything I can do or maybe you have an updated source code.

**Comment by ggadwa** [comment]
glew is an OpenGL extension library, it looks like that is the first thing you are missing.  The libraries are open source and you can google for it -- note that the version I looked at hasn't been updated since 2017, but I doubt it's changed that much.

**Comment by netkommander** [comment]
Do you mind linking it? I'm not sure what I'm missing in GLEW, I seem to have all the required libraries.

**Comment by netkommander** [comment]
By linking it, I mean I'm not sure where to put it. Do you put it in the GLEW directory structure?

**Comment by netkommander** [comment]
![image](https://user-images.githubusercontent.com/64513006/81366084-da0e3300-90b7-11ea-9d76-565d3cd88d97.png)
I updated the glew directories to the new versions but I'm still unsure what the problem is. What would I have to do in the linker to get them to read the input files, because each time I do that, it seems to tell me it can't find them?

**Comment by ggadwa** [comment]
I haven't looked at that code base in years, so I'm not exactly sure, but glew has an installation guide that might help.  http://glew.sourceforge.net/install.html

Basically, if I remember, there's probably a hard link in the VS project tree (in one of the folders somewhere) to the libs, and that's probably pointing somewhere that's not valid.  Find where that is (I don't have a PC with me right now) and then maybe delete those and re-add them.  You might want to check all those links, there's other libraries you might be missing.

**Comment by netkommander** [comment]
Hey man, I really do appreciate your help. I'll take a look some-more. The problem is that when I searched for your project on web archive, there were a lot of missing elements. I would really love to get working with this engine as it has a distinct graphical style that I love. Do you recommend using this engine yourself? Where exactly did the newer source code go? I only found this one 
https://github.com/prophile/dim3

Again, thanks for your help. I'll let you know if I run into something else.

**Comment by ggadwa** [comment]
I have no idea what that is, somebody must have uploaded the code!  The last changes I ever made to the code where at the old google code: https://code.google.com/archive/p/dim3/

I think a read only copy might still be there, I'm not sure what that guy did or what edits he might have made (that said, he might have made it better, I just don't know!)

At this point I wouldn't recommend the engine, though, it's just old, and not supported, and uses a lot of old technology.  I'm sure eventually you could update it but I don't know if it's worth it.  You're probably going to run into a good bit of trouble, that's one of the reasons this new project is the way it is.

**Comment by netkommander** [comment]
I'll take your word for it. It was fun learning more about how Visual Studio works. I'm going to go ahead and see if I can get your JS engine to run. I'm looking forward to the Kart feature :-)

**Comment by netkommander** [comment]
I'm going to try one more time with the new code you linked. Is there any reason why the Downloads aren't working? is that where the binaries went?

**Comment by ggadwa** [comment]
Yeah, I suspect that's where the binaries were.  My JS engine right now is very alpha, but it's playable.  It's got a ways to go.  It should be pretty easy to run and install, though I haven't spent a lot of time on the docs (as it's alpha state), if you try it, I'd be interested to see what trouble you might have.  The kart/reaper thing are actually part of the main demo now, I actually need to delete those projects :)

**Comment by netkommander** [comment]
I recently tried it, but the karts didn't work. It just gave me LOADING MAP and stuck there

**Comment by netkommander** [comment]
![image](https://user-images.githubusercontent.com/64513006/81367634-cebd0680-90bb-11ea-86b2-601250b678ab.png)
Reading the .README gets me this. I go to do this link but obviously it's down. Curious as to if I need these because it seems like getting the JavaScript core might be cumbersome.

**Comment by ggadwa** [comment]
Things are in flux, I'm working on the editor right now so I'm not sure what's broken, but the demo should work.  I'm going to delete the kart link, it's wrapped in the demo.  Yeah, you'd need those, and you'd need the DLLs.  Scruffy3D is still up at: http://www.klinksoftware.com/Scruffy/Scruffy3D_Win.zip which has the DLLs.  Heck, Scruffy3D is just a dim3 project.  No idea if it'll work on modern machines.

**Comment by netkommander** [comment]
Scruffy gives me this 
![image](https://user-images.githubusercontent.com/64513006/81369229-e26a6c00-90bf-11ea-8384-e2068a829f74.png)

**Comment by ggadwa** [comment]
Sorry: http://www.klinksoftware.com/Scruffy3D/Scruffy3D_Win.zip

**Comment by netkommander** [comment]
Thanks, will let you know how it compiles!

**Comment by netkommander** [comment]
Scruffy runs flawlessly on my machine. That's why I like engines like this, going to see if I can compile now
